spring:
  application:
    name: ai-recruitment-system
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash   # free tier, fast
            temperature: 0.7
            max-output-tokens: 2048
    retry:
      max-attempts: 1
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

# ----- App-level config -------------------------
app:
  redis:
    ai-cache-ttl: 3600    # cache AI responses for 1 hour (seconds)

#app:
#  jwt:
#    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#    expiration: 86400000   # 24 hours in milliseconds